version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: paul/datastore
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.1
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: urijs
    versions:
    - 1.19.6
  - dependency-name: webpack
    versions:
    - 4.46.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: case-sensitive-paths-webpack-plugin
    versions:
    - 2.4.0
  - dependency-name: react-google-login
    versions:
    - 5.2.2
  - dependency-name: react-responsive
    versions:
    - 8.2.0
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: postcss-flexbugs-fixes
    versions:
    - 5.0.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: bl
    versions:
    - 1.2.3
