export const GET_SOURCE = 'GET_SOURCE'
export const SET_SOURCE = 'SET_SOURCE'
export const DELETE_SOURCE = 'DELETE_SOURCE'
export const CACHE_SOURCE = 'CACHE_SOURCE'
export const SOURCE_DELETED = 'SOURCE_DELETED'
export const ERROR = 'ERROR'
