export const FETCH_TOPIC = 'FETCH_TOPIC'
export const SAVE_TOPIC = 'SAVE_TOPIC'
export const CACHE_TOPIC = 'CACHE_TOPIC'
export const GET_ALL_TOPICS = 'GET_ALL_TOPICS'
export const CLEAR_TOPICS = 'CLEAR_TOPICS'
