import { app, BrowserWindow, net, protocol, shell } from 'electron'
import url from 'url'
import { getWindowIdForGroup, initNodeDb, nodeDbRefs } from './nodeDb'
import { registerHandlers } from './eapi/handlers'
import { appState } from './eapi/handlers/state-handlers'
import { createMenus } from './menus'
import { mediaPath } from './eapi/handlers/file-handlers'

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

const windows = new Set<BrowserWindow>()

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit()
}

protocol.registerSchemesAsPrivileged([
  {
    scheme: 'dbdrive',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
    },
  },
])

export const createWindow = async () => {
  let x
  let y
  let height
  let width
  const currentWindow = BrowserWindow.getFocusedWindow()
  if (currentWindow) {
    const [currentWindowX, currentWindowY] = currentWindow.getPosition()
    x = currentWindowX + 24
    y = currentWindowY + 24
  }

  const _lastSize = appState.get('lastWindowSize')
  if (_lastSize) {
    width = _lastSize[0]
    height = _lastSize[1]
  }

  const window = new BrowserWindow({
    height,
    width,
    x,
    y,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      // enableRemoteModule: true,
    },
    titleBarStyle: 'hiddenInset',
  })

  window.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url)
    return { action: 'deny' }
  })

  // console.log('[Main]', Menu.getApplicationMenu())
  const menu = createMenus(window)

  // load the last active db, if one exists
  const lastActiveGroupId = appState.get('lastActiveGroupId')
  const localGroups = appState.get('localGroups')
  if (
    lastActiveGroupId &&
    localGroups?.find((g) => g._id === lastActiveGroupId) &&
    !getWindowIdForGroup(lastActiveGroupId)
  ) {
    await initNodeDb(window.id, lastActiveGroupId)
  } else {
    // clean up groups
    appState.set('lastActiveGroupId', null)
  }

  window.on('closed', async () => {
    console.log('[Main] shutting down the database...')
    try {
      await nodeDbRefs[window.id].current.close()
      delete nodeDbRefs[window.id]
    } catch (e) {
      console.warn('[Main] error shutting down database', e)
    }
    windows.delete(window)
  })

  window.on('focus', () => {
    if (nodeDbRefs[window.id]) {
      appState.set('lastActiveGroupId', nodeDbRefs[window.id].groupId)
    }
  })

  window.on('resized', () => {
    appState.set('lastWindowSize', window.getSize() as [number, number])
  })

  // Protocol handler for win32
  if (process.platform == 'win32') {
    // Keep only command line / deep linked arguments
    deeplinkingUrl = process.argv.slice(1)
  }

  // and load the index.html of the app.
  await window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)

  // Open the DevTools.
  // window.webContents.openDevTools()

  // Retrieve the command-line arguments
  // const args = process.argv
  // setTimeout(() => {
  //   logEverywhere(`[Main] args: ${args}`)
  //   // Check if a deep link argument is present
  //   const deepLinkArg = args.find((arg) => arg.startsWith('databyss://'))

  //   if (deepLinkArg) {
  //     // Handle the deep link
  //     logEverywhere(`[Main] deeplink args: ${deepLinkArg}`)
  //   }
  // }, 3000)

  windows.add(window)
  return window
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  protocol.handle('dbdrive', (request) => {
    const filePath = url.fileURLToPath(
      `file://${mediaPath()}/${request.url.slice('dbdrive://'.length)}`
    )
    console.log('[DDB] fetch', filePath)
    return net.fetch(`file://${filePath}`)
  })
  registerHandlers()
  createWindow()
})

// Deep linked url
let deeplinkingUrl

if (!app.isDefaultProtocolClient('databyss')) {
  // Define custom protocol handler. Deep linking works on packaged versions of the application!
  app.setAsDefaultProtocolClient('databyss')
}

function handleOpenUrl(url: string) {
  const _path = url.slice('databyss://'.length)
  const _pathParts = _path.split('/')
  if (_pathParts[0] === 'import') {
    getFirstWindow().webContents.send(
      'cmd-command',
      'importDatabase',
      _pathParts[1]
    )
  }
}

// Protocol handler for osx
app.on('open-url', function (event, url) {
  event.preventDefault()
  deeplinkingUrl = url
  setTimeout(() => {
    logEverywhere(`[Main] deeplinkingUrl: ${url}`)
    handleOpenUrl(url)
  }, 750)
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  app.quit()
})

app.on('will-quit', async (evt) => {
  //   if (nodeDbRef.groupId && nodeDbRef.current) {
  //     console.log('[Main] shutting down the database...')
  //     evt.preventDefault()
  //     try {
  //       nodeDbRef.groupId = null
  //       await nodeDbRef.current.close()
  //     } catch (e) {
  //       console.warn('[Main] error shutting down', e)
  //     }
  //     app.quit()
  //     return
  //   }
  console.log('[Main] goodbye!')
})

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

function getFirstWindow() {
  return Array.from(windows.values())[0]
}

// Log both at dev console and at running node console instance
function logEverywhere(s: string) {
  console.log(s)
  const _win = getFirstWindow()
  if (_win && _win.webContents) {
    _win.webContents.executeJavaScript(`console.log("${s}")`)
  }
}

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
