module.exports = [
  'Parergon (17)',
  'Restitutions (14)',
  'Khōra (10)',
  'On Touching—Jean-Luc Nancy (10)',
  'Dissemination (9)',
  'Of Grammatology (7)',
  'To Speculate—on “Freud” (6)',
  'Double Session (5)',
  'Le Facteur de la Vérité (5)',
  'The Animal That Therefore I Am (5)',
  'The Beast & the Sovereign (5)',
  '+R (4)',
  'Cartouches (4)',
  'Désistance (4)',
  'Cosmopolitanism and Forgiveness (3)',
  'Heidegger’s Hand (Geschlecht II), (3)',
  'Spurs: Nietzsche’s Styles (3)',
  'Adieu to Emmanuel Levinas (2)',
  'Gift of Death and Literature in Secret (2)',
  'Given Time (2)',
  'Hostipitality (2)',
  'Interpretations at War: Kant, the Jew, the German (2)',
  'Passions: “An Oblique Offering” (2)',
  'Psychoanalysis Searches the States of its Soul (2)',
  'Signature Event Context (2)',
  'The Archeology of the Frivolous: Reading Condillac (2)',
  'The Politics of Friendship (2)',
  'The Principle of Reason (2)',
  'A Silkworm of One’s Own (1)',
  'Aporias (1)',
]
