export const SET_ACTIVE_BLOCK_ID = 'SET_ACTIVE_BLOCK_ID'
export const SET_ACTIVE_BLOCK_TYPE = 'SET_ACTIVE_BLOCK_TYPE'
export const SET_ACTIVE_BLOCK_CONTENT = 'SET_ACTIVE_BLOCK_CONTENT'
export const SET_EDITABLE_STATE = 'SET_EDITABLE_STATE'
