export const LOAD_PAGE = 'LOAD_PAGE'
export const SAVE_PAGE = 'SAVE_PAGE'
export const PAGE_SAVED = 'PAGE_SAVED'
export const PAGE_LOADED = 'PAGE_LOADED'
export const SEED_PAGE = 'SEED_PAGE'
export const FETCHING_PAGES = '  FETCHING_PAGES'
export const PAGES_LOADED = 'PAGES_LOADED'
